Repository TetsuroAndo/42-minishell_v2, pull requests merged in 2025-05, with the labels that each got.

#64 norm makefile
  Makefile
Labels: Review effort 2/5

#65 Hotfix 0503
  src/builtin_cmds/unset.c
  src/modules/executer/exec_cmd.c
  src/modules/executer/exec_pipe.c
Labels: Review effort 2/5

#66 Fix env expand err
  src/modules/analyze_semantic/env_expand/proc_env.c
Labels: Review effort 2/5

#67 Hotfix parser
  Makefile
  scripts/clean_comments.py
  src/modules/analyze_semantic/proc_redr_errs.c
  src/modules/analyze_syntax/parse_primary.c
  src/modules/analyze_syntax/parser.c
Labels: Review effort 2/5

#70 fix: cp count_paren
  src/modules/analyze_lexical/tokenizer.c
  tests/try_semantic/Makefile
  tests/try_semantic/main.c
  tests/try_syntax/Makefile
  tests/try_syntax/main.c
  tests/tsunami_test.sh
  tests/tsunami_testcases
Labels: Review effort 2/5

#71 Befrev4 fix
  src/builtin_cmds/env.c
  src/builtin_cmds/export.c
  src/builtin_cmds/pwd.c
  src/modules/analyze_lexical/tokenizer.c
  src/modules/analyze_semantic/env_expand/proc_env.c
  tests/tsunami_compare_test.sh
  tests/tsunami_testcases
Labels: Review effort 3/5

#72 Fix wc
  Makefile
  inc/mod_sem.h
  src/builtin_cmds/export.c
  src/modules/analyze_lexical/tokenizer.c
  src/modules/analyze_semantic/env_expand/proc_env.c
  src/modules/analyze_semantic/proc_redr_errs.c
  src/modules/analyze_semantic/wildcard/wildcard.c
  src/modules/analyze_semantic/wildcard/wildcard_utils_2.c
  tests/tsunami_compare_test.sh
Labels: Review effort 2/5

#73 fix: debug
  Makefile
  inc/minishell.h
  inc/ms_debug.h
  src/core/debug/init_sh_proc.c
  src/core/shell_init.c
  src/minishell.c
  tests/tsunami_compare_test.sh
Labels: Review effort 2/5

#74 fix: parse_cmd loop
  src/modules/analyze_syntax/parse_primary.c
Labels: Review effort 2/5

#76 fix: inf roop
  src/modules/analyze_syntax/parse_primary.c
Labels: Review effort 2/5

#75 fix: env expr and debug and . err
  inc/ms_err.h
  src/lib/libms/ms_path/path_resolve.c
  src/minishell.c
  src/modules/analyze_semantic/env_expand/proc_env.c
Labels: Review effort 2/5

#77 fix: update author information in proc_env.c
  src/modules/analyze_semantic/env_expand/proc_env.c
Labels: Review effort 1/5

#78 norming
  Makefile
  inc/mod_sem.h
  inc/ms_err.h
  src/lib/libms/ms_path/path_resolve.c
  src/modules/analyze_lexical/tokenizer.c
  src/modules/analyze_lexical/validate_redirect_missing_arg.c
  src/modules/analyze_lexical/validate_special_chars.c
  src/modules/analyze_syntax/parse_primary.c
Labels: Review effort 2/5

#79 Hotfix heredoc expr
  Makefile
  inc/mod_sem.h
  inc/ms_token.h
  src/modules/analyze_lexical/debug_putlex.c
  src/modules/analyze_lexical/heredoc_loop.c
  src/modules/analyze_semantic/env_expand/extract_varname.c
  src/modules/analyze_semantic/env_expand/heredoc_env.c
  src/modules/analyze_semantic/env_expand/proc_env.c
  src/modules/analyze_semantic/quote/proc_quote.c
  src/modules/analyze_semantic/semantic.c
  src/modules/analyze_syntax/parse_primary.c
  tests/tsunami_compare_test.sh
  tests/tsunami_test.sh
Labels: Review effort 3/5

#80 ch: MIT -> GPL
  LICENSE
Labels: Review effort 1/5
