Repository TetsuroAndo/42-minishell_v2, pull requests merged in 2025-04, with the labels that each got.

#1 create init system and edit libms
  inc/core.h
  inc/libms.h
  inc/ms_readline.h
  src/core/initialize/initialize.c
  src/core/initialize/line_init.c
  src/core/initialize/shell_init.c
  src/core/shell_loop.c
  src/lib/libms/x_rappers/xitoa.c
  src/minishell.c
Labels: Review effort 3/5

#3 fix xitoa function call in line_init
  src/core/initialize/line_init.c
  src/core/initialize/shell_init.c
Labels: Review effort 1/5

#5 bug fix and fix shell_exit
  inc/core.h
  inc/libms.h
  inc/mod_lex.h
  src/core/initialize/line_init.c
  src/core/initialize/shell_init.c
  src/lib/libms/x_rappers/xclose.c
  src/lib/libms/x_rappers/xitoa.c
  src/minishell.c
Labels: Review effort 2/5

#6 fix: use close to xclose
  src/core/finalize/finalize.c
Labels: Review effort 2/5

#9 Solving the Circulation-Inclusion Problem
  inc/ms_readline.h
Labels: Review effort 1/5

#11 fix lexical and libms and makefile
  Makefile
  inc/core.h
  inc/libms.h
  src/core/initialize/shell_init.c
  src/core/readline/readline.c
  src/lib/libms/ms_free/xfree.c
  src/lib/libms/x_rappers/xdup.c
  src/lib/libms/x_rappers/xfork.c
  src/lib/libms/x_rappers/xitoa.c
  src/lib/libms/x_rappers/xlst.c
  src/lib/libms/x_rappers/xpipe.c
  src/minishell.c
  src/modules/analyze_lexical/allocate_token.c
  src/modules/analyze_lexical/debug_put_lex.c
  src/modules/analyze_lexical/lexer_handler.c
  src/modules/analyze_lexical/lexer_main_loop.c
  src/modules/analyze_lexical/tokenizer.c
  src/modules/analyze_semantic/.gitkeep
  src/modules/analyze_syntax/.gitkeep
  src/modules/analyze_syntax/parser.c
  src/modules/wildcard/expand_wildcard.c
Labels: Review effort 3/5

#15 progress syntax analyze system
  inc/core.h
  inc/libms.h
  inc/mod_syn.h
  inc/ms_ast.h
  inc/ms_token.h
  src/builtin_cmds/builtin_launcher.c
  src/lib/libms/ms_free/free_ast.c
  src/lib/libms/ms_free/free_token.c
  src/lib/libms/x_rappers/xmalloc.c
  src/modules/analyze_lexical/debug_putlex.c
  src/modules/analyze_syntax/debug_putsyn.c
  src/modules/analyze_syntax/parser.c
  src/modules/heredoc/.gitkeep
  tests/try_semantic/Makefile
  tests/try_semantic/main.c
  tests/try_syntax/Makefile
  tests/try_syntax/main.c
Labels: Review effort 3/5

#17 create debug mode header
  Makefile
  docs/debug_mode/READEME.md
  inc/core.h
  inc/ms_debug.h
  src/builtin_cmds/pwd.c
  src/modules/analyze_lexical/tokenizer.c
  src/modules/analyze_syntax/debug_putsyn.c
Labels: Review effort 2/5

#23 fix malloc in
  .gitignore
  src/modules/analyze_semantic/wildcard.c
Labels: Review effort 1/5

#30 fix: ms_envset finction and norm error
  inc/libms.h
  src/lib/libms/ms_env/key/ms_isactiveky.c
  src/lib/libms/ms_env/key/ms_partenvarg.c
  src/lib/libms/ms_env/ms_envcmp.c
  src/lib/libms/ms_env/ms_getenv.c
  src/lib/libms/ms_env/ms_setenv.c
  src/lib/libms/ms_env/ms_unset.c
  src/lib/libms/ms_env/value/ms_isactivevalue.c
Labels: Review effort 2/5

#31 Hotfix exit
  src/builtin_cmds/exit.c
Labels: Review effort 2/5

#33 Hotfix lex rdir validation
  inc/mod_lex.h
  inc/ms_err.h
  src/modules/analyze_lexical/tokenizer.c
  src/modules/analyze_lexical/validate_redirect_missing_arg.c
  src/modules/analyze_lexical/validate_special_chars.c
  src/modules/analyze_syntax/parser.c
Labels: Review effort 2/5

#35 add: __purint_export
  src/builtin_cmds/export.c
Labels: Review effort 2/5

#36 fix: paren lexer and semantic
  src/lib/libms/ms_string/xstrjoin.c
  src/modules/analyze_lexical/lexer_handler.c
  src/modules/analyze_lexical/tokenizer.c
  src/modules/analyze_lexical/validate_special_chars.c
  src/modules/analyze_semantic/semantic.c
Labels: Review effort 2/5

#37 Mod sem args
  inc/libms.h
  inc/ms_err.h
  src/lib/libms/ms_lst/ms_lstcopy.c
  src/lib/libms/ms_path/path_resolve.c
  src/modules/analyze_semantic/semantic.c
  src/modules/analyze_syntax/parser.c
Labels: Review effort 3/5

#38 fix: handle command not found with redirections
  src/lib/libms/ms_path/is_builtin.c
  src/modules/analyze_semantic/semantic.c
  src/modules/executer/mod_exec.c
Labels: Review effort 2/5

#40 Fix-here-doc
  inc/mod_sem.h
  inc/ms_err.h
  src/core/finalize/finalize.c
  src/core/signal/init_signals.c
  src/lib/libms/ms_string/trim_valid_quotes.c
  src/modules/analyze_semantic/semantic.c
  src/modules/analyze_semantic/split_with_quote.c
  src/modules/executer/mod_exec.c
Labels: Review effort 3/5

#41 fix:wildcard memory leak1
  src/modules/analyze_semantic/semantic.c
Labels: Review effort 1/5

#43 Feature mv heredoc lex
  inc/mod_lex.h
  inc/ms_err.h
  src/lib/libms/ms_gc/xfree_gc.c
  src/modules/analyze_lexical/allocate_token.c
  src/modules/analyze_lexical/heredoc_loop.c
  src/modules/analyze_lexical/lexer_handler.c
  src/modules/analyze_semantic/env_expand/.gitkeep
  src/modules/analyze_semantic/semantic.c
  src/modules/executer/mod_exec.c
Labels: Review effort 2/5

#45 Feature new expandenv
  inc/libms.h
  src/lib/libms/ms_gc/xfree_gc.c
  src/modules/analyze_semantic/env_expand/proc_env.c
  src/modules/analyze_semantic/semantic.c
Labels: Review effort 2/5

#48 fix: Support for no-value behavior.
  src/builtin_cmds/export.c
  src/lib/libms/ms_env/ms_setenv.c
Labels: Review effort 2/5

#51 retry
  src/lib/libms/ms_system/xfork.c
Labels: Review effort 2/5

#53 executer norming and refactoring
  inc/libms.h
  inc/mod_exec.h
  src/lib/libms/ms_system/set_cloexec.c
  src/minishell.c
  src/modules/executer/exec_bool.c
  src/modules/executer/exec_cmd.c
  src/modules/executer/exec_pipe.c
  src/modules/executer/exec_redirect.c
  src/modules/executer/exec_subsh.c
  src/modules/executer/exec_utils.c
  src/modules/executer/executer.c
  src/modules/executer/mod_exec.c.backup
Labels: Review effort 3/5

#54 norming lex
  inc/mod_lex.h
  src/modules/analyze_lexical/heredoc_loop.c
  src/modules/analyze_lexical/lexer_handler.c
  src/modules/analyze_lexical/lexer_main_loop.c
Labels: Review effort 1/5

#55 42 norm compliant core libms source code
  inc/core.h
  inc/libms.h
  inc/minishell.h
  inc/mod_exec.h
  inc/mod_lex.h
  inc/mod_sem.h
  inc/ms_debug.h
  inc/ms_err.h
  inc/ms_readline.h
  inc/ms_signal.h
  inc/ms_token.h
  src/core/debug/fin_sh.c
  src/core/debug/init_sh_proc.c
  src/core/debug/line_init_info.c
  src/core/finalize.c
  src/core/init_signals.c
  src/core/line_init.c
  src/core/readline.c
  src/core/shell_init.c
  src/lib/libms/ms_ast/free_ast.c
  src/lib/libms/ms_fd/xclose.c
  src/lib/libms/ms_fd/xdup.c
  src/lib/libms/ms_gc/ms_strjoin_gc.c
  src/lib/libms/ms_gc/ms_substr_gc.c
  src/lib/libms/ms_gc/xmalloc_gc.c
  src/lib/libms/ms_lst/xlst_from_strs.c
  src/lib/libms/ms_lst/xlst_to_strs.c
  src/lib/libms/ms_lst/xlstnew.c
  src/lib/libms/ms_path/is_builtin.c
  src/lib/libms/ms_path/path_cleancat.c
  src/lib/libms/ms_path/path_home.c
  src/lib/libms/ms_path/path_resolve.c
  src/lib/libms/ms_string/ms_put_ascii.c
  src/lib/libms/ms_string/ms_strdup.c
  src/lib/libms/ms_string/ms_substr.c
  src/lib/libms/ms_string/skip_dollar_paren.c
  src/lib/libms/ms_string/skip_spaces.c
  src/lib/libms/ms_string/xitoa.c
  src/lib/libms/ms_string/xsplit.c
  src/lib/libms/ms_string/xstrjoin.c
  src/lib/libms/ms_system/xmalloc.c
Labels: Review effort 2/5

#56 Norm fix lex
  inc/ms_err.h
  inc/ms_readline.h
  src/core/debug/init_sh_proc.c
  src/modules/analyze_lexical/heredoc_loop.c
Labels: Review effort 1/5

#57 fix:norm and error
  hard_sub_and.sh
  inc/builtin_cmds.h
  inc/core.h
  inc/libms.h
  inc/ms_ast.h
  src/builtin_cmds/builtin_launcher.c
  src/builtin_cmds/export.c
  src/modules/analyze_semantic/backup/astlst_backup.c
  src/modules/analyze_semantic/env_expand/proc_env.c
  src/modules/analyze_semantic/path/res_exec_path.c
  src/modules/analyze_semantic/quote/proc_quote.c
  src/modules/analyze_semantic/wildcard/wc_quote_parser.c
  src/modules/analyze_syntax/parser.c
  src/modules/ref_analyze_semantic/debug_putsem.c
  src/modules/ref_analyze_semantic/semantic.c
  src/modules/ref_analyze_semantic/split_with_quote.c
  src/modules/ref_analyze_semantic/wc_quote_parser.c
  src/modules/ref_analyze_semantic/wildcard.c
Labels: Review effort 2/5

#59 Mod sem norm
  inc/mod_sem.h
  src/builtin_cmds/unset.c
  src/lib/libms/ms_system/set_cloexec.c
  src/modules/analyze_semantic/split/split_utils.c
  src/modules/analyze_semantic/split/split_with_quote.c
  src/modules/analyze_semantic/wildcard/wc_parser_utils.c
  src/modules/analyze_semantic/wildcard/wc_quote_parser.c
  src/modules/analyze_semantic/wildcard/wildcard.c
  src/modules/analyze_semantic/wildcard/wildcard_utils.c
Labels: Review effort 2/5

#61 rm: backup tools
  Makefile.subm
  inc/mod_sem.h.backup
  inc/mod_syn.h.backup
  src/modules/analyze_syntax/parser.c.backup
  src/modules/executer/mod_exec.c.backup
Labels: Review effort 1/5

#62 Replacing forbidden func
  inc/core.h
  inc/libms.h
  inc/mod_sem.h
  src/lib/libms/ms_fd/ms_set_cloexec.c
  src/lib/libms/ms_fd/set_cloexec.c
  src/modules/analyze_semantic/wildcard/wc_quote_parser.c
  src/modules/analyze_semantic/wildcard/wildcard.c
  src/modules/analyze_semantic/wildcard/wildcard_utils.c
  src/modules/executer/exec_pipe.c
  src/modules/executer/exec_redirect.c
  src/modules/executer/exec_utils.c
Labels: Review effort 2/5

#63 Hotfix aftreview
  src/core/init_signals.c
  src/modules/analyze_semantic/split/split_utils.c
  src/modules/analyze_syntax/parse_primary.c
  src/modules/analyze_syntax/parser.c
Labels: Review effort 2/5
